### ISSUE TITLE
Add switch statements

### ISSUE THREAD

**Issue by vdka** [kai-language/kai#21]
2 Kinds of `switch` are planned.
```
x := 5
switch x {
case 5:
  print("It's five")

default:
  print("It's something other than five")
}

switch { // no subject, instead each case must be booleanesque
case x == 5:
  print("It's five")
default:
    print("It's something other than five")
}
```
Involves:

- [x] Add `switch`, `case` & `default` keywords to the lexer (`fallthrough`?)
- [x] Add `AstNode.stmtSwitch(subject: AstNode?, cases: [AstNode], fallback: AstNode?, SourceRange)` (something like this)
- [x] Checker ensure case values match the type of the `subject` (should there be one)
- [x] Otherwise ensure the case values are booleanesque
- [x] Code Gen

When there is no subject you can probably cheat LLVM and switch on the value `true`. The result of which would be that the first case that evaluates to `true` should match.

**Comment by BrettRToomey** [comment]
> Job's done!
