### ISSUE TITLE
Empty procedures don't compile

### ISSUE THREAD

**Issue by Joannis** [kai-language/kai#26]
```
main :: () -> void {

}
```

The above fails to compile.

**Comment by BrettRToomey** [comment]
@vdka seems related to the if block stuff.

**Comment by vdka** [comment]
This is an ambiguity in our chosen syntax. `{}` can be either a `stmtBlock` or a `litCompound` depending on context. I have resolved for this case, let's just be aware in case anything similar pops up anywhere else.
