### ISSUE TITLE
Warnings for unreachable code

### ISSUE THREAD

**Issue by vdka** [kai-language/kai#30]
This should be achievable through the parser.
Once you see a `return` keyword what should come after the things returned is something that terminates the current scope.
Usually this will be a `}`. However there are a number of cases where it is not so simple.

The easy case is when the current scope is a proc body. We know they *must* terminate in `}` and therefore (after getting return values and eating newlines and comments) we *must* see a `}`
Also easy is when `for` your current scope is a `for` body, it must also terminate in `}`
```
someProc :: () -> int {
    /* ... */
    return x
    x := 5 // ERROR: Unreachable statements
}
```

Harder is `if` statements which may be a block or maybe a single stmt
```
digitName :: (digit: u8) -> string, error {
    if digit > 9 return _, "Bad input"
    /* ... */
}
```

Also `switch` these can have their scope terminated by the keyword `case`
```
digitName :: (digit: u8) -> string, error {
    switch digit {
    case 0:
        return "Zero", nil

    case 1:
        return "One", nil

    /* ... */

    default:
        return _, "Bad input"
    }
}
```

**Comment by BrettRToomey** [comment]
@vdka while we're here, could we get a `Never` type/directive or should we just save that for later?

**Comment by vdka** [comment]
@BrettRToomey let's leave that for later. It will also likely be most suitable as `#unreachable` or something like that. Not sure, let's build the bridge once we need it.
