### ISSUE TITLE
Multiple statement parsing error

### ISSUE THREAD

**Issue by BrettRToomey** [kai-language/kai#44]
```
  1 #library "c" libc
  2 
  3 random :: () -> u64 {
  4     return 3
  5 }
  6 
  7 main :: () -> void {
  8     x, y := random(), random()
  9 
 10     printf("%d %d\n", x, y)
 11 }
```

The second `random()` call gets incorrectly parsed as `.identifier(random)`. It _seems_ to be related to LBP of `(`. Not sure what the best fix is, maybe scoring `)` and `,` the same? Thoughts, @vdka?

**Comment by vdka** [comment]
Is this still happening with the `lbp` tweak? (making `(`, `[` & `,` the same binding power)?
