### ISSUE TITLE
Polymorphics do not specialize correctly

### ISSUE THREAD

**Issue by vdka** [kai-language/kai#63]
When specializing a polymorphic a _strippedType_ should be generated.
This should not include *any* `ty.Polymorphics` currently it does.

The following function signature:

```
fn(arr: []$T, val: T) -> []T
```

Will produce a _strippedType_ that looks like this:

```
([]f32, T specialized to f32) -> ([]T specialized to f32)
```

for a call specializing with `[]f32{}`.
It should instead look like this:

```
([]f32, f32) -> ([]f32)
```

**Comment by BrettRToomey** [comment]
I believe #66 fixed this
